name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Package application for AWS Lambda
      run: |
        mkdir -p package
        pip install -r requirements.txt --target package/
        cp -r $(ls -A | grep -v package) package/
        cd package
        zip -r9 ../function.zip .
        cd ..

    - name: Deploy to AWS Lambda
      uses: appleboy/lambda-action@v0.1.4
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1
        function_name: testapi
        zip_file: function.zip
        debug: true
