name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - main  # Deploy only when the main branch is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install awscli

      - name: Package application
        run: |
          mkdir -p package
          pip install --target ./package -r requirements.txt
          cp -r $(ls | grep -v package) ./package/
          cd package && zip -r9 ../deploy.zip .

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:226401266262:function:testapi \
            --zip-file fileb://deploy.zip \
            --region us-east-1


