name: CI/CD

on:
  #Trigger workflow on push
  push:
    branches:
      - main

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Instal Python Virtual Env
        run: pip3 install virtualenv

      - name: Virutal ENV
        uses: actions/cache@v2
        id: cache-vevn
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: /
            ${{ runner.os }}-venv-
      
      - name: Activate Virutal ENV
        run: python -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt

      - name: Create archive of dependencies
        run: /
          cd ./venv/lib/python3.12/site-packages
          zip -r9 ../../../../api.zip
      - name: Add API Files to zip file
        run: cd ./api && zip -g ../api.zip -r .
      - name: Upload zipfile artifact
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api.zip
